spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sistema_examenes
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true